version: "3.8"
services:
  miner:
    build:
      context: ../src/miner
      dockerfile: Dockerfile
    command: python miner.py --host 0.0.0.0 --port 5000
    ports:
      - "5000:5000"

  aggregator:
    build:
      context: ../src/aggregator
      dockerfile: Dockerfile
    environment:
      - MINER_ENDPOINT=http://miner:5000
    ports:
      - "3000:3000"
    depends_on:
      - miner